### PR TITLE
fixed bug in image cropper that occured when original src image was l…

### PR DESCRIPTION
**Pull request by mcoppola**
…arger than 'full' size.  fixed by requesting 'original' size attachment for cropper, and by reimplementing scaleUp/scaleDown serialize methods

### CODE REVIEW

**Comment by mcoppola** [comment]
@colpanik @boutell could you check this PR?  especially Kerry if you could test in your projects that the cropper still works 👌.

I was seeing a bug with images larger than the "full" size.  The cropper coordinates wouldn't be relative to the original file.

**Comment by boutell** [comment]
Makes sense. It could be a big download, but cropping a tiny piece of a gigantic image is a legitimate use of our cropper, so it needs be there.

**Comment by mcoppola** [comment]
cool! thanks tom

**Comment by boutell** [comment]
Actually Matt, it looks like you added in some missing scaleUp/scaleDown
calls, which ought to make it work even if the image is not the original...

However, I think we should keep it this way because of the use case I
pointed out. (We have zooming enabled in the cropper right?)

On Fri, Jun 10, 2016 at 1:22 PM, Matthew Coppola <notifications@github.com>
wrote:

> cool! thanks tom
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/apostrophe/pull/590#issuecomment-225243301>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB9fQocwcYIU1Q2QatSoZrLawtlSYdRks5qKZ1MgaJpZM4IzJwD>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Pull request merged**
