### PR TITLE
Bugfix szint 2696 remove low search text and search summary

### PR DESCRIPTION
**Pull request by Vispercept**
```
/**
* Remove these fields, because the lead to errors on pages
* where several blog-posts were rendered.
*
* In our case it was the homepage were all blog-posts were rendered
* also some snippets (so called mediagalerys) were rendered on this page.
* This lead to a way to long searchSummary and lowSearchText because
* all contents of all articles and snippets were involved to this fields.
*
* Even worse is the fact, that some strings weren't escaped which lead to
* a destroyed js on client –> which leads to the fact that no one could
* add new pages for example...
*/
```

### CODE REVIEW

**Comment by boutell** [comment]
I understand your frustration, but throwing away useful data that helps
power the mongodb search and the summaries of search results is not the
answer. This would be a bc break. We need to improve the pruning that goes
on when making data about pages accessible on the front end. We also need
to look at why the escaping failed in this specific context.


On Wed, Dec 23, 2015 at 11:04 AM, Vispercept <notifications@github.com>
wrote:

> Closed #396 <https://github.com/punkave/apostrophe/pull/396>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/pull/396#event-499549443>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
I am not able to reproduce this issue in the sandbox. Please provide more complete directions to reproduce the problem so I can work on a safe fix. Thanks!

... Wait, it looks like you closed this issue already? Did you figure something out?

**Comment by Vispercept** [comment]
Hey Tom.

Yes I closed that pullrequest, because I didn't want to merge into the `apostrophe`-repository :-) I just wanted to merge in our _branch_. We had a very bad problem with this. All our data (yes nearly the whole database) were rendered to the frontend including all the information of all blog-posts in our database.

We found out that our problem was, that we passed all the blog-posts to the blogWidget as an option like so: `{{ aposSingleton(page, 'blogWidget', 'blog', { sources: [ 'title' ], allTeaser: allTeaser }) }}`. Surely this leads to the result, that the whole content of a blog-post were rendered in the frontend, because it was passed as an option...

We fixed this and now everything works fine.

**Comment by boutell** [comment]
Yes, you don't want to do that (:

In 0.6 we'll be more selective by default about what gets pushed into JSON.

On Wed, Feb 10, 2016 at 3:07 AM, Thomas König <notifications@github.com>
wrote:

> Hey Tom.
>
> Yes I closed that pullrequest, because I didn't want to merge into the
> apostrophe-repository :-) I just wanted to merge in our *branch*. We had
> a very bad problem with this. All our data (yes nearly the whole database)
> were rendered to the frontend including all the information of all
> blog-posts in our database.
>
> We found out that our problem was, that we passed all the blog-posts to
> the blogWidget as an option like so: {{ aposSingleton(page, 'blogWidget',
> 'blog', { sources: [ 'title' ], allTeaser: allTeaser }) }}. Surely this
> leads to the result, that the whole content of a blog-post were rendered in
> the frontend, because it was passed as an option...
>
> We fixed this and now everything works fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/pull/396#issuecomment-182247045>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Pull request closed without merging**
