### PR TITLE
TKT-919 / Position widget controls via options object in widget

### PR DESCRIPTION
**Pull request by mtthwmnc**
https://github.com/punkave/apostrophe/issues/919

Allows developers to position widget controls by passing in a 'position' property into a widget. The following values can be passed in:

- bottomLeft
- bottom RIght
- topRIght
- topLeft (default position, but developer may use it for granularity)

`{{ apos.singleton(data.global, 'footer', 'my-footer', { position: "bottomLeft" }) }}`

### CODE REVIEW

**Comment by abea** [comment]
On a purely code format point, the CSS formatting doesn't match the current stylelint config, though it looks to match the existing code. It might be an open question whether to incorporate those new formatting styles to Apostrophe.

**Comment by mtthwmnc** [comment]
@abea I was talking about this with @austinstarin – formatting in piecemeal as we we see it vs. maintaining the format of a project that doesn't use our current formatting practices is something we should formally discuss with the whole dev team

**Comment by austinstarin** [comment]
My vote would be to follow best practices and formatting within Apostrophe currently.

Maybe we can use our new house styles in the next version.

**Comment by abea** [comment]
That makes sense. Maybe we should create an issue to add a stylelint and eslint config to the project? I could create an issue and plan to do that.

**Comment by austinstarin** [comment]
@tom @stuartromanek This looks good to me?

**Comment by stuartromanek** [comment]
camelcase selectors? do we do that elsewhere? otherwise fine

**Comment by austinstarin** [comment]
Good point. This felt right though as a property you would pass in `{ position: topRight }`, for example.

**Comment by stuartromanek** [comment]
pass in JS' y camelcase config and convert it to hyphenated classes in the template with `apos.utils.cssName(string)`

**Comment by austinstarin** [comment]
👍

**Comment by boutell** [comment]
I think what you're proposing with your latest commit is that the values passed by the developer would be `bottom-left`, `top-right`, etc. to start with, rather than camelCased.

I'm fine with that if that is the intent.

**Comment by mtthwmnc** [comment]
I jumped the gun here - we're keeping the JS param camelCase and using a the nunjucks pipe filter {{ property | css }}

**Comment by stuartromanek** [comment]
Going to merge this for now

**Pull request merged**
