### PR TITLE
Updates to move notifications within modals to the lower right corner…

### PR DESCRIPTION
**Pull request by bobclewell**
… of the modal so that it doesn't block the buttons

### CODE REVIEW

**Comment by stuartromanek** [comment]
@bobclewell quick path to see this in action?

**Comment by boutell** [comment]
Oops, screenshot: https://www.dropbox.com/s/u5or2i8l5dw2j5e/87v-kcvx.png?raw=1

**Comment by bobclewell** [comment]
Fix the issue with the overlapping notifications and resubmit. 

To reproduce use `apos.notify('foo')` in the Console.

**Comment by bobclewell** [comment]
@boutell The styles have been updated and I confirm that the notification now stack correctly.

**Pull request merged**
