### PR TITLE
Moving the apostrophe buttons and menu above the WYSWYG editor.

### PR DESCRIPTION
**Pull request by bobclewell**
Specifically fixes a Michelin bug #73, found in their workflow testing.

### CODE REVIEW

**Comment by bobclewell** [comment]
@stuartromanek this should not have the odd behavior that you found with the pages menu and the modals.

**Comment by boutell** [comment]
So what happens if the dropdown style menu of the rich text editor is open and it overlaps  the workflow controls? In that situation the editor should win...

**Comment by bobclewell** [comment]
I think this looks right. Right? 
apostrophe_sandbox__home

**Comment by bobclewell** [comment]
This too...
apostrophe_sandbox__home

**Comment by boutell** [comment]
Any weird interactions when a modal is opened on top of the rich text editing controls?

How about notifications? Try apos.notify('hello') a few times in the console.

**Comment by bobclewell** [comment]
Yep. @boutell notifications look OK. 
apostrophe_sandbox__home

**Comment by bobclewell** [comment]
@boutell would you rather this is against the master branch? Even though it was found in the context of the workflow module, there's no code that depends on it. I can change the PR if you like.

**Comment by boutell** [comment]
Accepted — my Big Damn Project this afternoon is to merge this branch anyway so after that it won't matter, hooray

**Pull request merged**
