### PR TITLE
Updated old lodash alias to new function. contains -> includes

### PR DESCRIPTION
**Pull request by jsumnersmith**
@jth-  @boutell  @mcoppola 

Updated `_.contains` to `_.includes`

### CODE REVIEW

**Comment by jth-** [comment]
I may be missing something, but we spec `2.4.x` lodash in our `package.json`. I can't find `_.includes` in the `2.4.2` docs for lodash. https://github.com/lodash/lodash/blob/2.4.2/doc/README.md

**Comment by jsumnersmith** [comment]
OK. @jth- do you have a recommendation about this? The latest lodash is what I've got for my project. Should I pin back to 3.x?

**Comment by jth-** [comment]
I would probably pin it. I'd be very hesitant to update to lodash 4.x in 0.5, and that seems to be the other option. @boutell feel free to weigh in.

**Comment by jsumnersmith** [comment]
I'm down with this. I'll pin back locally and hopefully that'll fix it.

**Comment by boutell** [comment]
Although it's probably not a huge bc break, I think pinning is sensible for
0.5. Pin to ^3.0.0 so you still get 3.x patches.

On Mon, Feb 1, 2016 at 1:52 PM, Joel Smith <notifications@github.com> wrote:

> I'm down with this. I'll pin back locally and hopefully that'll fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/pull/417#issuecomment-178127138>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Pull request closed without merging**
