### PR TITLE
Size adjustments

### PR DESCRIPTION
**Pull request by stuartromanek**
lots of size and position adjustments for lower resolution displays. If you have ever thought 'all this looks too big' this branch is for you

### CODE REVIEW

**Comment by austinstarin** [comment]
Noticing the drawer is offset slightly for smaller viewports.

page-menu

**Comment by austinstarin** [comment]
This is contrived... But global menu transitions create odd, jumpy resizing with viewport shift.

**Comment by austinstarin** [comment]
Not sure if this detail is a result of anything but seeing it...

One line of text in this area doesn't align on baseline.

header

**Comment by austinstarin** [comment]
Getting a jumpy interaction with modal pills and search bar on resize.

header

**Comment by austinstarin** [comment]
Large viewport dropdown type size feels really big at 18px.

**Comment by stuartromanek** [comment]
just adjusted all of these @austinstarin .. feel free to pull and double check the grosser ones

**Comment by austinstarin** [comment]
Looks good! 👍

**Pull request merged**
